### ISSUE TITLE
大佬求助！

### ISSUE THREAD

**Issue by xinhaiyang** [ctripxchuang/dotnetfly#4]
![Uploading image.png…]()
        Child SP               IP Call Site
00000000157dc0b8 0000000077b29e3a [GCFrame: 00000000157dc0b8] 
00000000157dc2e0 0000000077b29e3a [GCFrame: 00000000157dc2e0] 
00000000157dc318 0000000077b29e3a [HelperMethodFrame: 00000000157dc318] System.Threading.Monitor.Enter(System.Object)
00000000157dc410 000007fe9b02aea9 System.ComponentModel.PropertyDescriptorCollection.Find(System.String, Boolean)
00000000157dc480 000007fe9b02b32c System.Data.XSDSchema.SetProperties(System.Object, System.Xml.XmlAttribute[])
00000000157dc4f0 000007fe9b043b3f System.Data.XSDSchema.HandleElementColumn(System.Xml.Schema.XmlSchemaElement, System.Data.DataTable, Boolean)

0:065> !syncblk
Index SyncBlock MonitorHeld Recursion Owning Thread Info  SyncBlock Owner
 1182 00000000131ebf88          278         0 0000000000000000     none    00000003ff781d18 System.ComponentModel.PropertyDescriptorCollection
-----------------------------
Total           347284
CCW             3
RCW             4
ComClassFactory 0
Free            334322

我的所有线程有卡在这个位置了，大佬有遇到过类似的情况吗

**Comment by ctripxchuang** [comment]
你这个是孤儿锁现象，可以加我微信：ixchuang ，  免费分析的。

**Comment by xinhaiyang** [comment]
感谢大佬
